name: Pygame test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Instal dependencies
        run: |
          python -m pip install  --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          flake8
          pytest